### PR TITLE
Add parser for MT940 transaction_details.

### PR DESCRIPTION
**Pull request by sweh**
Hi,

I wrote a small parser for the not readable MT940 `transaction_details`. Maybe python-fints is not the correct package for stuff like this, so feel free to point me to a better location.

An example what this PullRequest is trying to do:

If you have an example transaction_detail, which really is not very readable:

`177?00ONLINE-UEBERWEISUNG?109310?20SVWZ+Verwaltung. Briefmark
e?21n und  Umschlaege für MV, b?22estaetigt von AR in Sitzung?23a
m  03.06.17?24DATUM 10.06.2017, 10.47 UHR?251.TAN XXXXXX?26ABWA+L
euna Bungalowgemeinsc?27haft,  Roter See  e.V.?30NTSBDEB1XXX?31DE
6210011001XXXXXXXXXX?32Sebastian Wehrmann?34997`

This PullRequest will change the output of the `mt940.models.Transactions()` to

`{'Abweichender Auftraggeber': 'Leuna Bungalowgemeinschaft,  Roter See  e.V.',
 'Abweichender Empfänger': None,
 'Auftraggeber BIC': None,
 'Auftraggeber BLZ': 'NTSBDEB1XXX',
 'Auftraggeber Creditor ID': None,
 'Auftraggeber IBAN': None,
 'Auftraggeber Kontonummer': 'DE6210011001XXXXXXXXXX',
 'Auftraggeber Name': 'Sebastian Wehrmann',
 'Buchungstext': 'ONLINE-UEBERWEISUNG',
 'Compensation Amount': None,
 'Debtor Identifier bei SEPA Überweisung': None,
 'Empfänger: Name': None,
 'End to End Referenz': None,
 'FRST / ONE / OFF /RECC': None,
 'Geschäftsvorfall-Code': '177',
 'Kundenreferenz': None,
 'Mandatsdatum': None,
 'Mandatsreferenz': None,
 'Original Amount': None,
 'Primanota': '9310',
 'Purpose Code': None,
 'Rücklastschriften': None,
 'SEPA Mandatsänderung: alte SEPA CI': None,
 'SEPA Mandatsänderung: alte SEPA Mandatsreferenz': None,
 'SEPA Settlement Tag für R- Message': None,
 'Verwendungszweck': 'Verwaltung. Briefmarken und  Umschlaege für MV, bestaetigt von AR in Sitzungam  03.06.17DATUM 10.06.2017, 10.47 UHR1.TAN XXXXXX',
 'Zusätzl. Verwendungszweckangaben': None}`

### CODE REVIEW

**Comment by raphaelm** [comment]
Hi! First of all, thanks a lot. I believe the correct place for this is the mt940 package, and indeed there is an issue on that package for this. Maybe join the discussion there and bring that forward? https://github.com/WoLpH/mt940/issues/30

I'm happy if I can assist you with that in any way.

**Comment by sweh** [comment]
Hi raphaelm,

thanks for pointing me to the discussion on the mt940 package. If I get the processor integrated into the mt940 package, will you accept a pull request that allows me to select the processor when retrieving transactions via `fints`?

Kind regards,
  Sebastian

**Comment by raphaelm** [comment]
> If I get the processor integrated into the mt940 package, will you accept a pull request that allows me to select the processor when retrieving transactions via fints?

Absolutely! (If it isn't going to be default in mt940)

**Comment by chbndrhnns** [comment]
@raphaelm Could you maybe require `mta-940==4.8.1` for your package to get those recent improvements?

**Comment by FelixSchwarz** [comment]
@chbndrhnns I don't think that is the correct solution. You can always do this in your install but python-fints also works with older versions of mta-940 so I don't think version 4.8.1 should be required in general.

**Comment by FelixSchwarz** [comment]
Btw: the newest version of mta-940 just parses the "transaction_details" regardless of specifc gvcs. If you are not using the latest mt-940 git, see https://github.com/WoLpH/mt940/issues/49#issuecomment-340603135 for a temporary solution.

**Pull request closed without merging**
