### PR TITLE
preparing data to fix error in mt940 DateTimeIndication

### PR DESCRIPTION
**Pull request by myaicloud**

### CODE REVIEW

**Comment by raphaelm** [comment]
Hi,

thanks for your input! Is there a reason you removed all the relative imports?

Cheers
Raphael

**Comment by myaicloud** [comment]
I imported python-fints by path, so the relative imports doesn't work. I guess there are not relative imports needed?

**Comment by raphaelm** [comment]
What do you mean by "by path"? Within the module, relative imports should work fine. I'm against the change in imports you propose, as it makes it unclear that e.g. ``utils`` is part of the package and not an external dependency. If you have a real case of relative imports not working, we should replace ``.utils`` with the absolute path, e.g. ``fints.utils``, instead of just ``utils``.

**Comment by myaicloud** [comment]
I import the fints project by:
```
sys.path.append('<myprojectpath>/pythonfints/fints')
from client import FinTS3PinTanClient
```
Then i get an error by import a relative path inside fints. Or do you recommend me to do it in a different way?

**Comment by raphaelm** [comment]
I recommend you to take the time and learn about ``pip``, which makes these things a lot easier. Also, your method works fine on your machine, but not once you share your code with others, as the paths will probably not match.

However, to make your method work, the following should help:

```
sys.path.append('<myprojectpath>/pythonfints')
from fints.client import FinTS3PinTanClient
```

This way, you're importing fints as a package and all the relative imports inside should work.

**Comment by myaicloud** [comment]
I used pip and the code faild. So i forked and fixed it.
I changed the paths and my import method. Now it works fine.

**Comment by raphaelm** [comment]
Top. Thanks!

**Pull request merged**
