### PR TITLE
Comdirect support

### PR DESCRIPTION
**Pull request by rhn**
This is just a copy of https://github.com/raphaelm/python-fints/pull/129 for easy merging.

The previous author bumped the version because the compatibility with older Pythons was left behind. (I don't know where exactly.)

This rebased version is also compatible with Python 3.10.

### CODE REVIEW

**Comment by raphaelm** [comment]
Uh, thanks, I'll try to find some time to test this. I don't have a comdirect account, but I do have phototan, so I'd be curious if it works with others as well

**Comment by Ferenc-** [comment]
@rhn
I am under the impression, that the `decode_phototan_image` is already [implemented here](https://github.com/raphaelm/python-fints/blob/bc1c81e0a42be245c6af24bb0885ce1b2407bd2a/fints/client.py#L1063). 
I have been using `challenge_matrix[1]` for quite a while without any issue. Do we really need `decode_phototan_image`?

**Comment by raphaelm** [comment]
I pushed a little cleanup – please don't mix version number increases with other changes!

**Comment by raphaelm** [comment]
I reverted after the merge since indeed it was duplicate but now we at least have it covered in docs!

**Pull request merged**
