### PR TITLE
Add SEPA-instant payment functionality

### PR DESCRIPTION
**Pull request by yniverz**
I added a simple and crude way of using the SEPA Instant payment (Sofort Überweisung) functionality with a simple kw argument.

By no means a perfect implementation but it is a nice refinement to the present simple_sepa_transfer functionality in my opinion.

### CODE REVIEW

**Comment by raphaelm** [comment]
The outgoing segments look okay, but do we need to handle the return segments like HIIPZ specifically? Do we need to handle the new return code ``3270 Auftrag wird als Standard-SEPA-Überweisung bearbeitet`` specially?

**Comment by yniverz** [comment]
Thank you for bringing that to attention, after your message I checked the documentation again, and I discovered that the 3270 functionality (and its origin issue) is only supported by Segmentversion 2 (I assume the transaction would just fail in version 1). I have adjusted the code to now use version 2.

Version 2 requires another DataElement to disclose if the user permits automatic conversion to normal SEPA transfer if instant payments are not supported by the receiving institute though, so i assume that anyone who uses this function is willing for that to happen and permanently set `allow_convert_sepa_transfer` to True ("J").

Along with this, at least to my limited knowledge there is no special handling required for return code 3270.

**Comment by yniverz** [comment]
While an implementation of HKIPZ and HKIPM version 2 needs a bit more work (because it returns HIIPZ ver. 2), the current commit (version 1) is tested and works.

Version 1 does not appear to support `Umwandlung nach SEPA-Überweisung zulässig` and does not have the return code `3270`, so does not appear to need any further return code handling.

**Comment by raphaelm** [comment]
Okay, fair enough :)

**Pull request merged**
