### PR TITLE
add util function to decode photoTAN images

### PR DESCRIPTION
**Pull request by morremeyer**
This adds a utility function to decode photoTAN images.

It was tested against comdirect bank successfully with two accounts.

It also:

* updates the list of tested accounts and security functions as comdirect is what I used to test against
* drops support for 3.4 and 3.5 as elementpath doesn’t support those versions anymore
* adds 3.7+ to the tests

### CODE REVIEW

**Comment by Ferenc-** [comment]
I can confirm that @morremeyer 's code works as expected with the [new tested bank](https://github.com/raphaelm/python-fints/pull/129/commits/0852626cfda35601a4711ea3ebd23f1f000bd522#L13).
And this is a huge step forward in the usability of python-fints, at least for me personally. 
@raphaelm is there a chance that this PR would be accepted?  

BTW, this is how I am testing it.:
```
from PIL import Image

with f:
    if f.init_tan_response:
        print("A TAN is required", f.init_tan_response.challenge)
        hitan6 = f.init_tan_response.tan_request
        challenge_hhduc = hitan6.challenge_hhduc
        data = decode_phototan_image(challenge_hhduc)        
        
        bytes_io = io.BytesIO(data['image'])
        Image.open(bytes_io).show()
   
        tan = input('Please enter TAN:')
        f.send_tan(f.init_tan_response, tan)

    # Fetch accounts
    print('Fetching accounts')
    accounts = f.get_sepa_accounts()
    print(accounts)
````

**Comment by raphaelm** [comment]
yes, this will most likely be merged! just need to find some time for the project, it always takes some time to readjust to all the fints crazyness :)

**Review by tloebhard — APPROVED** [review]
Thank you, that solves #127

**Review by tloebhard — COMMENTED** [review]
Isn't image decoding already done in https://github.com/raphaelm/python-fints/blob/bc1c81e0a42be245c6af24bb0885ce1b2407bd2a/fints/client.py#L1063 ?

I just use ....challenge_matrix[1] as image and it works fine for comdirect photoTAN.

**Comment by Ferenc-** [comment]
> Isn't image decoding already done in
> 
> https://github.com/raphaelm/python-fints/blob/bc1c81e0a42be245c6af24bb0885ce1b2407bd2a/fints/client.py#L1063
> ?
> 
> I just use ....challenge_matrix[1] as image and it works fine for comdirect photoTAN.

True! Now I can confirm that using `challenge_matrix[1] ` is perfectly fine. At least for my purposes.
So @morremeyer, is it possible that this PR is not needed after all?

**Comment by christiankoch1** [comment]
Anyone knows a library for decoding a PhotoTAN into string for C#?
Or knows who using a python library within C#-project?
Thank you :-)

**Comment by HFT-turnet** [comment]
> Isn't image decoding already done in https://github.com/raphaelm/python-fints/blob/bc1c81e0a42be245c6af24bb0885ce1b2407bd2a/fints/client.py#L1063 ?
> 
> 
> 
> I just use ....challenge_matrix[1] as image and it works fine for comdirect photoTAN.

It does indeed work with Deutsche Bank. Thanks for indicating it!

**Comment by rhn** [comment]
I can confirm that this works with Comdirect, at least when it comes to account statements.

The conflict in this branch is trivial, I fixed it: https://github.com/raphaelm/python-fints/pull/142

**Comment by Ferenc-** [comment]
> I can confirm that this works with Comdirect, at least when it comes to account statements.
> 
> The conflict in this branch is trivial, I fixed it: #142

I am sorry but why? As @tloebhard pointed out, this has already been implemented, and I am using it daily.
So what is the point of re-implementing? I think this PR should be closed.

**Comment by raphaelm** [comment]
Closed as superseded by #142, h

**Pull request closed without merging**
